baseURL = "https://yourusername.github.io/"
languageCode = "vi"
title = "Blog Lập Trình Mạng - Java & JavaScript"
theme = "custom-theme"
defaultContentLanguage = "vi"
enableRobotsTXT = true

[pagination]
  pagerSize = 10
enableGitInfo = true

[params]
  author = "Phạm Tùng Dương"
  description = "Blog chuyên sâu về lập trình mạng với Java và JavaScript, chia sẻ kiến thức và kinh nghiệm thực tế"
  keywords = "Java, JavaScript, Lập trình mạng, Cisco, Network Programming, Socket Programming"
  
[taxonomies]
  category = "categories"
  tag = "tags"
  
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About Me"
    url = "/about/"
    weight = 3
  [[menu.main]]
    identifier = "certificates"
    name = "Certificates"
    url = "/certificates/"
    weight = 4

[markup]
  [markup.highlight]
    style = "github-dark"
    codeFences = true
    lineNos = true

